
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import StartScreen from '@/comps/StartScreen'
import { useState } from 'react'
import GameBoard from '@/comps/GameBoard'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [startGame, setStartGame] = useState(true);

  function handleStart() {
    setStartGame(prev => prev ? prev == false : prev == prev);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main className={styles.index__body}>
        {startGame ? <StartScreen handleStart={handleStart}/> : <GameBoard/>}
     </main>
    </>
  )
}
